package(default_visibility = ["PUBLIC"])

filegroup(
    name = "github_release_asset",
    srcs = ["github_release_asset.build_defs"],
    visibility = ["PUBLIC"],
)

filegroup(
    name = "remote",
    srcs = ["remote.build_defs"],
    visibility = ["PUBLIC"],
)

filegroup(
    name = "proto_extensions",
    srcs = ["proto_extensions.build_defs"],
    visibility = ["PUBLIC"],
)
