plugin_repo(
    name = "go",
    revision = "v1.17.3",
)

plugin_repo(
    name = "proto",
    revision = "v0.4.0",
)

plugin_repo(
    name = "go_proto",
    plugin = "go-proto",
    revision = "v0.3.0",
)
